### ISSUE TITLE
Participants video is not stable

### ISSUE THREAD

**Issue by sachinbhatt1** [coloquium/kollokvium#10]
1) Once we are connected through any room, some times participants video automatically disappears then again we have to refresh the complete page to see the video but this is not a proper solution for this issue.

2) Video streaming is not stable, audio is audible but can't see the video. 

3) Application is not browser compatible it's not working in Opera, Edge, Safari (can't see the local video even after giving access to camera and microphone) it's only working on chrome and firefox browser only.

**Comment by MagnusThor** [comment]
Thanks for your comments / feedback,  this is my response

1 . yes, we have noticed this.  Iit's causes by the fact that the connection (P2P) is weak , or drops, this ends as you decribe.  There is a fix comming, reconnecting ( detecting lost connections ).  

2. This is tricky, i do think this i caused by the fact that connection is bad  and/or the media device reslolution 

This is the default constraints;  ( We gonna dig deeper into this )

```
  static defaultConstraints: MediaStreamConstraints = {

        video: {
            width: { min: 640, ideal: 1280 },
            height: { min: 400, ideal: 720 },
            frameRate: 25
        }, audio: true,
    };
```
3. We are aware of this.   Safari is connected to `MediaStreamConstraints` , fix is comming.   Tested on succesfully  ( working ), on Chrome (Windows, osX, Linux ) ,  Chrome ( Safari osX, iOS) , Firefox ( Windows, Linux ) as well ass Chrome for Andriod and Samsung Browser.     


Once agin,  Thanks for valuable feedback

**Comment by MagnusThor** [comment]
Regarding the Safari on OSX , problems, i manage to reproduce after a while ( old Mac Book pro ), i made a fix, that is deployed on dev ( test site ) ,  Now kollokium will show an alert  if getUserMedia fails, it will instruct user to do use "fail safe settings" , just doing a` {video:true, audio:true} `  constraint request.   I pushed to dev, and it shall be available at https://dev-wss.kollokvium.net/

**Comment by sachinbhatt1** [comment]
when we can expect the fix on the above points???
