### ISSUE TITLE
Very very feature

### ISSUE THREAD

**Issue by sachinbhatt1** [coloquium/kollokvium#12]
Hi kollokvium Team,

1. I just want to know can we identify the **Host(means who has started the meeting)**, why I am asking this because it's very important to know who is hosting the meeting if there are _n_ number of participants. 
2. Can we change the **display pattern of local or remote videos**? because it's **very difficult to see the shared screen of other participants** due to the display grid size. there should be an option like if we click on a particular remote video and it should display in big size so that we can see a clear picture of a shared screen or person. Or you can give some other alternate.
3. As I have mentioned in my earlier issue **video streaming is not stable**. if someone has a network issue or some other issue remote videos are disappearing automatically.

**Comment by MagnusThor** [comment]
Hi,

Regarding feature (**host, meeting organizer** ) , yes, that is somethng that we have in plan, not a big thing to implement, but we haven seen the use_case yet :-)    Thaks for explaning.

 **display pattern of local or remote videos**, is there is a an "full-screen-button" ( see icon )  on each remote video in the grid,  unfortunatly difficult to see, bit to next release  .      This brings the selected video to fullscreen .   We are also adding hotkeys (where i press 1...9 , or arrow right, left ) , comming in a release next by.

**video streaming is not stable** , yes, its a tricky thing to test, and fiddle with.   But a reconnect to meeting .  I guess when you say _remote videos are disappearing automatically_.  you say that all videos is lost?  even thosse who has a connection?  Please describe the scenario more,  how many participants etc.   I would be greatful!

**Comment by MagnusThor** [comment]
Fixed. See ActiveSpeaker view. closng due to no answers

**Comment by sachinbhatt1** [comment]
> I
![colc](https://user-images.githubusercontent.com/11180552/86450472-3e0b4b80-bd37-11ea-8938-fb511876d7f2.jpeg)

**video streaming is not stable** when I am saying this means I think we were 10 participants connected through but some times on our main screen all video lost means participants are there but I am not able to see their video then we need to refresh all page to see participants again. Please see the attached image. and i need one more help from i will be more thank full to you can you guide me how to configure this application on IIS 8.5.

**Comment by MagnusThor** [comment]
Hi, @sachinbhatt1 , thaks for making things a bit mor clear to me,  this kind of feedback is very helpfull.

I see that toy run mobile, and yes i have seen simular probems,  it may be caused by network limitations.   Network issues can _partly_ be solved by you adding a TURN server of your own to the `iceServers`  in the `settings.json`.

We have choosen to nut use TURN ( relay of streams) as this will end up a cost for the project, and as we dont have any funding & sponsors we cannot do so right now.  

I also do belive the problem is the current defaultConstraints is set to HD, and as Kollokvium dont have a middleman  due to privacy the device struggles dealing with 10 ibound streams as well as outbound,  as this is a mobile device , 

I would recomend you to try 360p(nHD) as default settings, maybe also narrow down , a bit more of participants , a more adaptive way, that can easily be implemented , i also see you run an older version, based on the backgroundm as well woud concider adding 1-n more STUN servers  in the config, maybe local nes for your country / region ?

try use 360p , by modifying `UserSettings.ts ` ( line 88 )


      video: {
                    width: { min: 320, max: 1280, ideal: 640 },
                    height: { min: 240, max: 720, ideal: 360 },
                    frameRate: 30,
                    facingMode: { ideal: shouldFaceUser ? 'user' : 'environment' },
                }, audio: true,
            };


I also do belive more recent versions is a bit more stable regarding > 4 participants.  

Regarding the quesioon about "how configure this application on IIS 8.5", i suggest you create a new issue,  we have a master of such things that may be able to help you out ( ping @tibor19 )

Kind regards

Magnus

**Comment by sachinbhatt1** [comment]
Thanks, @MagnusThor  for the quick response. 
Actually It's not the issue with mobile its also with the laptop screen. I think there is some limitation with the application also like no of participants, Internet connection bandwidth.
and you were talking about the TURN server this is a paid server or what?

**Comment by MagnusThor** [comment]
Hi,  yes a TURN server will be a cost.  TURN server will relay data,  if STUN failes to connect.

 And we did some test on saturday,  both 1-n many, as well as long-lasting meetings,  and found some problms, not like those you have reported.  I dod infact mamage to reprocude it, and done some updates.   Updates avaliale here, master branch as well as they are deployed to https://kollokvium.se 

The application dont (should not) have any limitations,  i trided to make some changes, to the underlaying RTCPeerConnetions, that may improve connectivity.   

Kind regards

Magnus

**Comment by MagnusThor** [comment]
@sachinbhatt1  we done some updates to the signaling as well as how we deal with MediaStreams.     Give me a shout if you still have this problem, or if you dont care anymore :)
