### ISSUE TITLE
How to Configure this Application on IIS 8.5 Server

### ISSUE THREAD

**Issue by sachinbhatt1** [coloquium/kollokvium#25]
Hi Team,

I need your assistance with the configuration of this code on the IIS Server. Kindly Guide me how we can configure this on  **Windows server 2012 (IIS 8.5)**.
Thanks in advance.

**Comment by MagnusThor** [comment]
In order to run node on IIS you probably need a middleware for node, as IIS is ASP.NET etc.  but is possible.  i also recommend you to look at azure websites,  we are using that, but thats a cloud-service.

I just google ( run node js on iis 8.5) , there is for instance this at stack;

https://stackoverflow.com/questions/46266609/host-node-js-on-windows-server-iis

I did run node js on iis using iisnode a while ago, so iisnode is also a tip from me,  i guess if you ask @tibor19 i will probably point you in the same direction.

**Comment by MagnusThor** [comment]
@sachinbhatt1 as there is no reply i reckon this can be closed.
